startup = [
	'alias la = ls --long',
	'alias cfg = nvim (config path)',
	'alias en  = enter',
	'alias dots = enter ~/Dropbox/Dev/.config/',
	'alias je = nvim ./justfile',
	'alias wg = winget',
	'alias wgi = sudo winget install',
	'alias wgu = sudo winget uninstall',

	'def edit [...f] {if (($f | length) > 0) {start ($f | str collect " ") -a neovide} {start . -a neovide} }',
	'def backup_year [YEAR] {robocopy $"F:\\Arquivo HS\\Arquivo\\($YEAR)" $"\\Backup\\sda2\\henrique\\fotos\\arquivo\\($YEAR)" /MT:4 /Z /XO /XX /XN /S}',

	"let-env STARSHIP_CONFIG = $'(echo ~/Dropbox/Dev/.config/starship/config.toml | path expand)'",
	"let-env STARSHIP_CACHE = $'(echo ~/Dropbox/Dev/.cache/starship/ | path expand)'",
	"let HOME = $'(echo ~/Dropbox/Dev/ | path expand)'",

	'alias activate = load-env (venv .venv)',
	'alias deactivate = source "C:/util/venvs/deactivate.nu"',
	"source C:/util/venvs/activate.nu",

	"source C:/util/starship/init.nu",
]

skip_welcome_message = true
table_mode = "rounded"
pivot_mode = "always" # auto, always, never
disable_table_indexes = true

prompt = 'starship_prompt'

path = [
	# LLVM CLANG
	"C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/Llvm/x64/bin",
	# CMAKE
	"C:/Program Files/CMake/bin",
	#AAA
	"C:/Program Files/Python310",
	"C:/Program Files/Python310/Scripts",
	"C:/Program Files/KopiaUI/resources/server/",
]

[env]
STARSHIP_SHELL  = "nu"
WINKITS = 'C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0'
FTQ = 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64'

